#!/usr/bin/env python3

import sys, os
from matplotlib import pyplot as plt
import numpy as np

def run():
    times = []
    memory = []
    with open(sys.argv[1]) as memfile:
        for line in memfile:
            itime, imem = [int(x) for x in line.split()]
            times.append(itime)
            memory.append(imem)

    tarray = np.array(times)
    tarray -= tarray.min()
    mem_mb = np.array(memory, dtype='d') / 1000
    plt.scatter(tarray, mem_mb)
    plt.xlabel('time [seconds]')
    plt.ylabel('Memory Use [MB]')
    plt.savefig('memory-use.pdf')

if __name__ == '__main__':
    run()

